/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soft252cw.secretary;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import soft252cw.signin;

/**
 *
 * @author akeyorekon
 */
public class secretarypage extends javax.swing.JFrame {

    /**
     * Creates new form secretarypage
     */
    
    
     DefaultListModel<String>listModel;
   DefaultListModel<String>listModel1;
   DefaultListModel<String>listModel2;
   DefaultListModel<String>listModel3;
   DefaultListModel<String>listModel4;
     /* Creates new form viewhistory1
     */
  
    public secretarypage() {
        initComponents();
          listModel = new DefaultListModel<>();
        listModel1 = new DefaultListModel<>();
        listModel2 = new DefaultListModel<>();
        listModel3 = new DefaultListModel<>();
        listModel4 = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oldpatient = new javax.swing.JList<>();
        patdisp = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        reqapproval = new javax.swing.JTextField();
        acceptreq = new javax.swing.JButton();
        SHOWOLD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctojlist = new javax.swing.JList<>();
        patdisp1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        shodoc = new javax.swing.JButton();
        docshowed = new javax.swing.JTextField();
        dayb = new javax.swing.JComboBox<>();
        monthb = new javax.swing.JComboBox<>();
        yearb = new javax.swing.JComboBox<>();
        submitapp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        updatedpat = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        medlist = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        confpatient = new javax.swing.JButton();
        upvalue = new javax.swing.JTextField();
        medselected1 = new javax.swing.JButton();
        medtext = new javax.swing.JTextField();
        givethemed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(oldpatient);

        patdisp.setText("DISPLAY ");
        patdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patdispActionPerformed(evt);
            }
        });

        jLabel1.setText("display request");

        acceptreq.setText("accept patient request");
        acceptreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptreqActionPerformed(evt);
            }
        });

        SHOWOLD.setText("select and show patient request");
        SHOWOLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWOLDActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(doctojlist);

        patdisp1.setText("DISPLAY ");
        patdisp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patdisp1ActionPerformed(evt);
            }
        });

        jLabel2.setText("show free doctor");

        shodoc.setText("select and show the doctor");
        shodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shodocActionPerformed(evt);
            }
        });

        dayb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        yearb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021" }));

        submitapp.setText("submit appointment");
        submitapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitappActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(updatedpat);

        jButton3.setText("show updated");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(medlist);

        jButton4.setText("show med");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        confpatient.setText("CONF PATIENT");
        confpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confpatientActionPerformed(evt);
            }
        });

        medselected1.setText("select med");
        medselected1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medselected1ActionPerformed(evt);
            }
        });

        medtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medtextActionPerformed(evt);
            }
        });

        givethemed.setText("GIVE THE MED");
        givethemed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                givethemedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(patdisp)))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SHOWOLD)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(reqapproval, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(patdisp1))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acceptreq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(shodoc))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dayb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(monthb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yearb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(docshowed, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(submitapp)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confpatient)
                                    .addComponent(medselected1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upvalue)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(medtext, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(givethemed, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(patdisp))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(SHOWOLD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(reqapproval, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patdisp1))
                            .addGap(24, 24, 24)
                            .addComponent(acceptreq, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(shodoc)
                            .addGap(18, 18, 18)
                            .addComponent(docshowed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dayb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(monthb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(submitapp))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(157, 157, 157))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(confpatient)
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(medselected1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(medtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37)
                                    .addComponent(givethemed, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(upvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patdispActionPerformed
       // LOAD patient data to the jlist

        BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("patienthistory.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel1.addElement(ss);//add data to list model

            }
            oldpatient.setModel(listModel1);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_patdispActionPerformed

    private void SHOWOLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWOLDActionPerformed
         String Value=(String)oldpatient.getSelectedValue();
        reqapproval.setText(Value);
    }//GEN-LAST:event_SHOWOLDActionPerformed

    private void acceptreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptreqActionPerformed
        try {
            
            FileWriter f = new FileWriter("patientacceptedwithoutnewappointment.txt",true);
             f.write("\n"+reqapproval.getText()+" accepted acc ");
           
             
       
            
           
        
            f.close();
             System.out.println(" WAS CREATED SUCCESFULLY");
            
            
        } catch (IOException ex) {
            Logger.getLogger(secretarypage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_acceptreqActionPerformed

    private void patdisp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patdisp1ActionPerformed
         BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("doctor.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel.addElement(ss);//add data to list model

            }
            doctojlist.setModel(listModel);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_patdisp1ActionPerformed

    private void shodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shodocActionPerformed
         String Value=(String)doctojlist.getSelectedValue();
        docshowed.setText(Value);
    }//GEN-LAST:event_shodocActionPerformed

    private void submitappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitappActionPerformed
         try {
            
            FileWriter f = new FileWriter("patientacceptedplusappointment.txt",true);
             f.write("\n"+reqapproval.getText()+",");
          
             
          
             
            f.write("  a new reservation have been made by the secretary on the "+dayb.getSelectedItem().toString()+"/"+monthb.getSelectedItem().toString()+"/"+yearb.getSelectedItem().toString()+".");
            
            f.close();
             System.out.println(" new acc req+book created");
            
            
        } catch (IOException ex) {
            Logger.getLogger(signin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitappActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // LOAD patient data to the jlist

        BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("patientacceptedplusappointment.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel3.addElement(ss);//add data to list model

            }
            updatedpat.setModel(listModel3);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void confpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confpatientActionPerformed
        String Value=(String)updatedpat.getSelectedValue();
        upvalue.setText(Value);
    }//GEN-LAST:event_confpatientActionPerformed

    private void medselected1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medselected1ActionPerformed
         String Value=(String)medlist.getSelectedValue();
        medtext.setText(Value);
    }//GEN-LAST:event_medselected1ActionPerformed

    private void medtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medtextActionPerformed

    private void givethemedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_givethemedActionPerformed
       try {
            
            FileWriter f = new FileWriter("patientthatreceivedmedfromsecretary.txt",true);
             f.write("\n"+upvalue.getText()+",");
          
             
          
             
            f.write("secretary gave this" +medtext.getText()+"to you.");
            
            f.close();
             System.out.println(upvalue.getText()+medtext.getText());
            
            
        } catch (IOException ex) {
            Logger.getLogger(signin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_givethemedActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // LOAD patient data to the jlist

        BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("doctormed.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel4.addElement(ss);//add data to list model

            }
            medlist.setModel(listModel4);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secretarypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secretarypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secretarypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secretarypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secretarypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SHOWOLD;
    private javax.swing.JButton acceptreq;
    private javax.swing.JButton confpatient;
    private javax.swing.JComboBox<String> dayb;
    private javax.swing.JTextField docshowed;
    private javax.swing.JList<String> doctojlist;
    private javax.swing.JButton givethemed;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> medlist;
    private javax.swing.JButton medselected1;
    private javax.swing.JTextField medtext;
    private javax.swing.JComboBox<String> monthb;
    private javax.swing.JList<String> oldpatient;
    private javax.swing.JToggleButton patdisp;
    private javax.swing.JToggleButton patdisp1;
    private javax.swing.JTextField reqapproval;
    private javax.swing.JButton shodoc;
    private javax.swing.JButton submitapp;
    private javax.swing.JList<String> updatedpat;
    private javax.swing.JTextField upvalue;
    private javax.swing.JComboBox<String> yearb;
    // End of variables declaration//GEN-END:variables
}
