/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soft252cw;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author akeyorekon
 */
public class signin extends javax.swing.JFrame {

    /**
     * Creates new form signin
     */
    
     DefaultListModel<String>listModel;
     DefaultListModel<String>listModel1;
   
  
        
  
    
    public signin() {
        
        initComponents();
        listModel = new DefaultListModel<>();
        listModel1 = new DefaultListModel<>();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rating = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DT = new javax.swing.JComboBox<>();
        DN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ST = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SA = new javax.swing.JTextField();
        AS = new javax.swing.JButton();
        AD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctor = new javax.swing.JList<>();
        ratselect = new javax.swing.JButton();
        vidoctor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listofdoc = new javax.swing.JList<>();
        docchoose = new javax.swing.JButton();
        docchoosen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        feedbackadmin = new javax.swing.JTextField();
        displaylistofdoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingActionPerformed(evt);
            }
        });

        jLabel10.setText("ROLE DOCTOR");

        DT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D" }));
        DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTActionPerformed(evt);
            }
        });

        jLabel1.setText("DR NAME");

        jLabel2.setText("DR PASSWORD");

        jLabel3.setText("DR ADDRESS");

        jLabel11.setText("ROLE SECRETARY");

        ST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S" }));

        jLabel4.setText("SR NAME");

        jLabel5.setText("SR PASSWORD");

        jLabel6.setText("SR ADDRESS");

        AS.setText("ADD SECRETARY");
        AS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASActionPerformed(evt);
            }
        });

        AD.setText("ADD DOCTOR");
        AD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(doctor);

        ratselect.setText("select rating");
        ratselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratselectActionPerformed(evt);
            }
        });

        vidoctor.setText("show");
        vidoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidoctorActionPerformed(evt);
            }
        });

        jLabel7.setText("list of doctor");

        jLabel8.setText("ALL PATIENT RATING BY THE DOCTOR");

        jScrollPane2.setViewportView(listofdoc);

        docchoose.setText("choose doctor");
        docchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docchooseActionPerformed(evt);
            }
        });

        jButton1.setText("SEND FEEDBACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Write your FeedBack");

        displaylistofdoc.setText("display");
        displaylistofdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaylistofdocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(vidoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(ratselect))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jLabel9)))
                                .addGap(0, 261, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(feedbackadmin)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(docchoosen, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                            .addComponent(rating))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(docchoose)
                                .addGap(261, 261, 261))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(displaylistofdoc)
                                            .addComponent(jLabel7))
                                        .addGap(419, 419, 419))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel1))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(58, 58, 58)
                                                        .addComponent(DT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(DN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DP, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(AD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AS)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SN)
                                            .addComponent(SP)
                                            .addComponent(SA, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(DT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(SN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(SA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(AS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(AD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(displaylistofdoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(ratselect)
                                .addGap(18, 18, 18)
                                .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(docchoose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(docchoosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(15, 15, 15)
                                .addComponent(feedbackadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(vidoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(225, 225, 225))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(146, 146, 146))))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public static void removeFromFile(String removeTerm) throws IOException
    {
           Scanner x;
           String TempFile ="temp.txt";
           File oldfile =new File("user.txt");
           File newfile = new File(TempFile);
           String ID ="";//String name="";String Age ="";
           try{
               FileWriter fw =new FileWriter(TempFile,true);
               BufferedWriter bw=new BufferedWriter(fw);
               PrintWriter pw= new PrintWriter (bw);
               x =new Scanner(new File("user.txt"));
               
               while(x.hasNext())
               {
                   ID= x.nextLine();
                   if(!ID.equals(removeTerm))
                   {
                       pw.println(ID);
                   }
               }
               x.close();
               pw.flush();
               pw.close();
               oldfile.delete();
               File dump =new File("user.txt");
               newfile.renameTo(dump);
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null,e);
           }
    }
    private void ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingActionPerformed

    private void DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTActionPerformed

    private void ASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASActionPerformed
        try {
            FileWriter fw = new FileWriter("secretary.txt",true);
            FileWriter f = new FileWriter("secretaryhistory.txt",true);
            
            
             f.write("\n"+" Secretary : "+ST.getSelectedItem().toString()+",");
            fw.write(SN.getText()+"\n");
             
            f.write(" name : "+SN.getText()+",");
            fw.write(SP.getText()+"\n");
        
            

            f.write(" ADDRESS : "+SA.getText());

            fw.close();
            f.close();
            System.out.println("SECRETARY WAS CREATED SUCCESFULLY");
            f.close();
            System.out.println(" WAS CREATED SUCCESFULLY");

        } catch (IOException ex) {
            Logger.getLogger(logadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_ASActionPerformed

    private void ADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADActionPerformed
           try {
            FileWriter fw = new FileWriter("doctorlogin.txt",true);
            FileWriter f = new FileWriter("doctor.txt",true);
            f.write("\n"+DT.getSelectedItem().toString()+".");
            fw.write(DN.getText()+"\n");
            f.write("DR "+DN.getText()+",");
            fw.write(DP.getText()+"\n");
             f.write(DA.getText());

            fw.close();
            System.out.println("DOCTOR WAS CREATED SUCCESFULLY");
            f.close();
            System.out.println(" WAS CREATED SUCCESFULLY");

        } catch (IOException ex) {
            Logger.getLogger(logadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ADActionPerformed

    private void ratselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratselectActionPerformed
       String Value=(String)doctor.getSelectedValue();
        rating.setText(Value);
    }//GEN-LAST:event_ratselectActionPerformed

    private void vidoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidoctorActionPerformed
        // LOAD patient data to the jlist

        BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("patienthistory.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel1.addElement(ss);//add data to list model

            }
            doctor.setModel(listModel1);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_vidoctorActionPerformed

    private void displaylistofdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaylistofdocActionPerformed
        // LOAD patient data to the jlist

        BufferedReader sr =null;
        try{
            sr =new BufferedReader(new FileReader("patientprescription.txt"));

            int val =Integer.parseInt(sr.readLine());// read the first line from file
            for (int i = 0; i < val; i++) {
                String ss =sr.readLine();//read the data
                listModel.addElement(ss);//add data to list model

            }
            listofdoc.setModel(listModel);// store listmodel to jlist

        }
        catch(Exception e){
            System.out.println(""+e);

        }
    }//GEN-LAST:event_displaylistofdocActionPerformed

    private void docchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docchooseActionPerformed
        String Value=(String)listofdoc.getSelectedValue();
        docchoosen.setText(Value);
    }//GEN-LAST:event_docchooseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          
            FileWriter fa = new FileWriter("adminfeedback.txt",true);
          
            fa.write("\n"+"Base on your rating for the "+rating.getText()+" , ");
            fa.write( docchoosen.getText()+" , ");
             fa.write(" i would like to give you my own rating: " + feedbackadmin.getText()+ " ." );
              
             
           
            
           
            
            fa.close();
             System.out.println(" Rating succesful ");
       
            
            
        } catch (IOException ex) {
            Logger.getLogger(signin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }
    
    
        
            // TODO add your handling code here:
//            FileReader fr = new FileReader("user.txt");
//            BufferedReader br = new BufferedReader(fr);
//            String aLine = "";
//            
//            while((aLine = br.readLine()) != null)
//            {
//                users.addElement(aLine);
//            }
//            user123.setModel(users);
//            br.close();
//            fr.close();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AD;
    private javax.swing.JButton AS;
    private javax.swing.JTextField DA;
    private javax.swing.JTextField DN;
    private javax.swing.JTextField DP;
    private javax.swing.JComboBox<String> DT;
    private javax.swing.JTextField SA;
    private javax.swing.JTextField SN;
    private javax.swing.JTextField SP;
    private javax.swing.JComboBox<String> ST;
    private javax.swing.JButton displaylistofdoc;
    private javax.swing.JButton docchoose;
    private javax.swing.JTextField docchoosen;
    private javax.swing.JList<String> doctor;
    private javax.swing.JTextField feedbackadmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listofdoc;
    private javax.swing.JTextField rating;
    private javax.swing.JButton ratselect;
    private javax.swing.JButton vidoctor;
    // End of variables declaration//GEN-END:variables
}
